import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import { AntConfigProvider } from "@/components/shared/AntConfigProvider"
import { SmoothScroll } from "@/components/shared/SmoothScroller"

const perfectlyNineties = localFont({
  src: [
    { path: "./fonts/perfectly-nineties-black.otf" },
    { path: "./fonts/perfectly-nineties-regular.otf", weight: "400" },
  ],
  variable: "--font-perfectly-nineties",
})

const pixter = localFont({
  src: [
    { path: "./fonts/Pixter-Display-Bold.ttf", weight: "600" },
    { path: "./fonts/Pixter-Display.ttf" },
  ],
  variable: "--font-pixter-display",
})

const sequel = localFont({
  src: [{ path: "./fonts/Sequel-Sans-Book-Disp.ttf" }],
  variable: "--font-sequel-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixter.variable} ${sequel.variable} ${sequel.className} ${perfectlyNineties.variable} antialiased`}
      >
        <AntConfigProvider>
          <SmoothScroll>{children}</SmoothScroll>
        </AntConfigProvider>
      </body>
    </html>
  )
}
