import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import "@rainbow-me/rainbowkit/styles.css"
import { AntConfigProvider } from "@/components/shared/AntConfigProvider"
import { SmoothScroll } from "@/components/shared/SmoothScroller"
import { TanstackQueryProvider } from "@/components/providers/TanstackProvider"
import { Wagmi } from "@/components/providers/Wagmi"
import { RainbowKit } from "@/components/providers/RainbowKit"
import { Toaster } from "@/components/ui/sonner"

const perfectlyNineties = localFont({
  src: [
    { path: "./fonts/perfectly-nineties-black.otf" },
    { path: "./fonts/perfectly-nineties-regular.otf", weight: "400" },
  ],
  variable: "--font-perfectly-nineties",
})

const pixter = localFont({
  src: [
    { path: "./fonts/Pixter-Display-Bold.ttf", weight: "600" },
    { path: "./fonts/Pixter-Display.ttf" },
  ],
  variable: "--font-pixter-display",
})

const sequel = localFont({
  src: [{ path: "./fonts/Sequel-Sans-Book-Disp.ttf" }],
  variable: "--font-sequel-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#27330f"></meta>
      <body
        className={`${pixter.variable} ${sequel.variable} ${sequel.className} ${perfectlyNineties.variable} antialiased`}
      >
        <Wagmi>
          <TanstackQueryProvider>
            <RainbowKit>
              <AntConfigProvider>
                <SmoothScroll>{children}</SmoothScroll>
              </AntConfigProvider>
              <Toaster />
            </RainbowKit>
          </TanstackQueryProvider>
        </Wagmi>
      </body>
    </html>
  )
}
