import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import { AntConfigProvider } from "@/components/shared/AntConfigProvider"
import { SmoothScroll } from "@/components/shared/SmoothScroller"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const perfectlyNineties = localFont({
  src: [
    { path: "./fonts/perfectly-nineties-black.otf" },
    { path: "./fonts/perfectly-nineties-regular.otf", weight: "400" },
  ],
  variable: "--font-perfectly-nineties",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${perfectlyNineties.variable} antialiased`}
      >
        <AntConfigProvider>
          <SmoothScroll>{children}</SmoothScroll>
        </AntConfigProvider>
      </body>
    </html>
  )
}
