-- AlterTable
ALTER TABLE "public"."Ad" ALTER COLUMN "poolAmount" DROP DEFAULT,
ALTER COLUMN "poolAmount" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "minAmount" DROP DEFAULT,
ALTER COLUMN "minAmount" SET DATA TYPE DECIMAL(78,0),
ALTER COLUMN "maxAmount" DROP DEFAULT,
ALTER COLUMN "maxAmount" SET DATA TYPE DECIMAL(78,0);

-- AlterTable
ALTER TABLE "public"."AdLock" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(78,0);
